In [17]:
import os
from pprint import pprint

In [18]:
for vul in ['IoU', 'RE', 'TD'][:1]:
    data_loc = f"../../Dataset/{vul}/SolidiFi_{vul}"
    out_doc = os.path.join(data_loc, "draft")

In [19]:
os.listdir(out_doc)

['uncommented_renamed_buggy_26.sol',
 'uncommented_renamed_buggy_32.sol',
 'uncommented_buggy_6.sol',
 'uncommented_buggy_7.sol',
 'uncommented_renamed_buggy_33.sol',
 'uncommented_renamed_buggy_27.sol',
 'uncommented_renamed_buggy_31.sol',
 'uncommented_renamed_buggy_25.sol',
 'uncommented_renamed_buggy_19.sol',
 'uncommented_renamed_buggy_18.sol',
 'uncommented_renamed_buggy_24.sol',
 'uncommented_renamed_buggy_30.sol',
 'uncommented_renamed_buggy_34.sol',
 'uncommented_renamed_buggy_7.sol',
 'uncommented_renamed_buggy_6.sol',
 'uncommented_renamed_buggy_23.sol',
 'uncommented_renamed_buggy_37.sol',
 'uncommented_renamed_buggy_36.sol',
 'uncommented_renamed_buggy_22.sol',
 'uncommented_buggy_37.sol',
 'uncommented_buggy_23.sol',
 'uncommented_buggy_22.sol',
 'uncommented_buggy_36.sol',
 'uncommented_buggy_34.sol',
 'uncommented_buggy_19.sol',
 'uncommented_buggy_25.sol',
 'uncommented_buggy_31.sol',
 'uncommented_buggy_30.sol',
 'uncommented_buggy_24.sol',
 'uncommented_buggy_18.sol',
 'uncommented_buggy_32.sol',
 'uncommented_buggy_26.sol',
 'uncommented_buggy_27.sol',
 'uncommented_buggy_33.sol']

In [35]:
import os

def get_file_stats(filepath):
    with open(filepath, 'r') as file:
        content = file.read()
    lines_of_code = len(content.splitlines())
    number_of_function = content.count('function')
    number_of_event = content.count('event')
    number_of_struct = content.count('struct')
    number_of_library = content.count('library')
    number_of_mapping = content.count('mapping')
    return {
        "# lines of codes": lines_of_code,
        "number of function": number_of_function,
        "number of event": number_of_event,
        "number of struct": number_of_struct,
        "number of library": number_of_library,
        "number of mapping": number_of_mapping
    }

def compare_files(out_doc):
    files = os.listdir(out_doc)
    files.sort()
    report = []

    file_pairs = {}
    for file in files:
        if file.startswith('uncommented_renamed_buggy_'):
            number = file.split('_')[-1].split('.')[0]
            file_pairs.setdefault(number, {})['renamed'] = file
        elif file.startswith('uncommented_buggy_'):
            number = file.split('_')[-1].split('.')[0]
            file_pairs.setdefault(number, {})['original'] = file

    for number, pair in file_pairs.items():
        if 'original' in pair and 'renamed' in pair:
            original_stats = get_file_stats(os.path.join(out_doc, pair['original']))
            renamed_stats = get_file_stats(os.path.join(out_doc, pair['renamed']))
            report.append([
                {pair['original']: original_stats},
                {pair['renamed']: renamed_stats}
            ])

    return report

def compare_infos(data):
    if len(data) != 2:
        raise ValueError("Data must contain exactly two dictionaries.")
    
    nested_dict1 = next(iter(data[0].values()))
    nested_dict2 = next(iter(data[1].values()))
    
    are_equal = nested_dict1 == nested_dict2
    
    differences = {}
    if not are_equal:
        differences = {k: (nested_dict1[k], nested_dict2[k]) for k in nested_dict1 if nested_dict1[k] != nested_dict2[k]}
    
    return are_equal, differences




for vul in ['IoU', 'RE', 'TD']:
    data_loc = f"../../Dataset/{vul}/SolidiFi_{vul}"
    out_doc = os.path.join(data_loc, "draft")
    if os.path.exists(out_doc):
        report = compare_files(out_doc)
        for comparison in report:
            matched, difference = compare_infos(comparison)

            if not matched:
                print(list(comparison[0].keys())[0])
                pprint(difference)
                print(20*"_")

uncommented_buggy_12.sol
{'# lines of codes': (259, 261),
 'number of function': (33, 34),
 'number of struct': (2, 3)}
____________________
uncommented_buggy_15.sol
{'# lines of codes': (92, 89)}
____________________
uncommented_buggy_19.sol
{'# lines of codes': (350, 380)}
____________________
uncommented_buggy_21.sol
{'# lines of codes': (443, 365),
 'number of function': (46, 32),
 'number of mapping': (20, 16)}
____________________
uncommented_buggy_22.sol
{'# lines of codes': (490, 489)}
____________________
uncommented_buggy_24.sol
{'# lines of codes': (466, 465)}
____________________
uncommented_buggy_25.sol
{'# lines of codes': (283, 313)}
____________________
uncommented_buggy_26.sol
{'# lines of codes': (270, 266)}
____________________
uncommented_buggy_29.sol
{'# lines of codes': (265, 280)}
____________________
uncommented_buggy_32.sol
{'# lines of codes': (103, 301),
 'number of event': (2, 4),
 'number of function': (13, 54),
 'number of mapping': (3, 15)}
____________________
uncommented_buggy_35.sol
{'# lines of codes': (219, 215)}
____________________
uncommented_buggy_36.sol
{'# lines of codes': (473, 249),
 'number of function': (66, 22),
 'number of mapping': (18, 1)}
____________________
uncommented_buggy_38.sol
{'# lines of codes': (377, 205),
 'number of function': (64, 29),
 'number of mapping': (16, 4)}
____________________
uncommented_buggy_40.sol
{'# lines of codes': (299, 324)}
____________________
uncommented_buggy_42.sol
{'# lines of codes': (288, 287)}
____________________
uncommented_buggy_44.sol
{'# lines of codes': (411, 407), 'number of event': (6, 14)}
____________________
uncommented_buggy_45.sol
{'# lines of codes': (136, 132)}
____________________
uncommented_buggy_46.sol
{'# lines of codes': (143, 84),
 'number of function': (15, 6),
 'number of mapping': (3, 1)}
____________________
uncommented_buggy_49.sol
{'number of function': (13, 19)}
____________________
uncommented_buggy_50.sol
{'# lines of codes': (331, 155),
 'number of function': (47, 20),
 'number of mapping': (12, 3)}
____________________
uncommented_buggy_6.sol
{'# lines of codes': (355, 293), 'number of function': (55, 41)}
____________________
uncommented_buggy_7.sol
{'# lines of codes': (362, 364)}
____________________
uncommented_buggy_19.sol
{'# lines of codes': (145, 174), 'number of struct': (2, 3)}
____________________
uncommented_buggy_25.sol
{'# lines of codes': (312, 334)}
____________________

In [37]:
import os
import pandas as pd

def get_file_stats(filepath):
    with open(filepath, 'r') as file:
        content = file.read()
    lines_of_code = len(content.splitlines())
    number_of_function = content.count('function')
    number_of_event = content.count('event')
    number_of_struct = content.count('struct')
    number_of_library = content.count('library')
    return {
        "# lines of codes": lines_of_code,
        "number of function": number_of_function,
        "number of event": number_of_event,
        "number of struct": number_of_struct,
        "number of library": number_of_library
    }

def compare_files(out_doc):
    files = os.listdir(out_doc)
    files.sort()
    data = []

    file_pairs = {}
    for file in files:
        if file.startswith('uncommented_renamed_buggy_'):
            number = file.split('_')[-1].split('.')[0]
            file_pairs.setdefault(number, {})['renamed'] = file
        elif file.startswith('uncommented_buggy_'):
            number = file.split('_')[-1].split('.')[0]
            file_pairs.setdefault(number, {})['original'] = file

    for number, pair in file_pairs.items():
        if 'original' in pair and 'renamed' in pair:
            original_stats = get_file_stats(os.path.join(out_doc, pair['original']))
            renamed_stats = get_file_stats(os.path.join(out_doc, pair['renamed']))
            data.append({
                "file_number": number,
                "original_file": pair['original'],
                "renamed_file": pair['renamed'],
                "original_lines_of_code": original_stats["# lines of codes"],
                "renamed_lines_of_code": renamed_stats["# lines of codes"],
                "original_number_of_function": original_stats["number of function"],
                "renamed_number_of_function": renamed_stats["number of function"],
                "original_number_of_event": original_stats["number of event"],
                "renamed_number_of_event": renamed_stats["number of event"],
                "original_number_of_struct": original_stats["number of struct"],
                "renamed_number_of_struct": renamed_stats["number of struct"],
                "original_number_of_library": original_stats["number of library"],
                "renamed_number_of_library": renamed_stats["number of library"],
            })

    df = pd.DataFrame(data)
    return df

# Example usage
for vul in ['IoU', 'RE', 'TD']:
    data_loc = f"../../Dataset/{vul}/SolidiFi_{vul}"
    out_doc = os.path.join(data_loc, "draft")
    if os.path.exists(out_doc):
        df = compare_files(out_doc)
        display(df)

,file_number,original_file,renamed_file,original_lines_of_code,renamed_lines_of_code,original_number_of_function,renamed_number_of_function,original_number_of_event,renamed_number_of_event,original_number_of_struct,renamed_number_of_struct,original_number_of_library,renamed_number_of_library
0,10,uncommented_buggy_10.sol,uncommented_renamed_buggy_10.sol,39,39,4,4,2,2,0,0,0,0
1,11,uncommented_buggy_11.sol,uncommented_renamed_buggy_11.sol,132,132,22,22,3,3,2,2,1,1
2,12,uncommented_buggy_12.sol,uncommented_renamed_buggy_12.sol,259,261,33,34,3,3,2,3,1,1
3,13,uncommented_buggy_13.sol,uncommented_renamed_buggy_13.sol,89,89,8,8,3,3,1,1,0,0
4,14,uncommented_buggy_14.sol,uncommented_renamed_buggy_14.sol,156,156,25,25,3,3,2,2,1,1
5,15,uncommented_buggy_15.sol,uncommented_renamed_buggy_15.sol,92,89,8,8,3,3,1,1,0,0
6,16,uncommented_buggy_16.sol,uncommented_renamed_buggy_16.sol,247,247,32,32,6,6,3,3,1,1
7,17,uncommented_buggy_17.sol,uncommented_renamed_buggy_17.sol,185,185,19,19,3,3,4,4,1,1
8,18,uncommented_buggy_18.sol,uncommented_renamed_buggy_18.sol,278,278,32,32,4,4,2,2,2,2
9,19,uncommented_buggy_19.sol,uncommented_renamed_buggy_19.sol,350,380,65,65,0,0,2,2,1,1
10,20,uncommented_buggy_20.sol,uncommented_renamed_buggy_20.sol,441,441,58,58,5,5,3,3,0,0
11,21,uncommented_buggy_21.sol,uncommented_renamed_buggy_21.sol,443,365,46,32,1,1,3,3,1,1
12,22,uncommented_buggy_22.sol,uncommented_renamed_buggy_22.sol,490,489,66,66,8,8,4,4,1,1
13,23,uncommented_buggy_23.sol,uncommented_renamed_buggy_23.sol,331,331,62,62,2,2,2,2,1,1
14,24,uncommented_buggy_24.sol,uncommented_renamed_buggy_24.sol,466,465,53,53,0,0,4,4,1,1
15,25,uncommented_buggy_25.sol,uncommented_renamed_buggy_25.sol,283,313,35,35,7,7,3,3,0,0
16,26,uncommented_buggy_26.sol,uncommented_renamed_buggy_26.sol,270,266,53,53,4,4,1,1,1,1
17,27,uncommented_buggy_27.sol,uncommented_renamed_buggy_27.sol,289,289,35,35,7,7,3,3,1,1
18,28,uncommented_buggy_28.sol,uncommented_renamed_buggy_28.sol,199,199,28,28,2,2,2,2,1,1
19,29,uncommented_buggy_29.sol,uncommented_renamed_buggy_29.sol,265,280,35,35,3,3,4,4,1,1
20,30,uncommented_buggy_30.sol,uncommented_renamed_buggy_30.sol,531,531,77,77,15,15,6,6,3,3
21,31,uncommented_buggy_31.sol,uncommented_renamed_buggy_31.sol,210,210,26,26,2,2,3,3,1,1
22,32,uncommented_buggy_32.sol,uncommented_renamed_buggy_32.sol,103,301,13,54,2,4,1,1,1,1
23,33,uncommented_buggy_33.sol,uncommented_renamed_buggy_33.sol,285,285,47,47,3,3,3,3,1,1
24,34,uncommented_buggy_34.sol,uncommented_renamed_buggy_34.sol,458,458,70,70,3,3,3,3,1,1
25,35,uncommented_buggy_35.sol,uncommented_renamed_buggy_35.sol,219,215,27,27,7,7,2,2,1,1
26,36,uncommented_buggy_36.sol,uncommented_renamed_buggy_36.sol,473,249,66,22,8,8,4,4,1,1
27,37,uncommented_buggy_37.sol,uncommented_renamed_buggy_37.sol,131,131,22,22,3,3,2,2,0,0
28,38,uncommented_buggy_38.sol,uncommented_renamed_buggy_38.sol,377,205,64,29,2,2,2,2,1,1
29,39,uncommented_buggy_39.sol,uncommented_renamed_buggy_39.sol,120,120,16,16,2,2,1,1,0,0
30,40,uncommented_buggy_40.sol,uncommented_renamed_buggy_40.sol,299,324,57,57,2,2,2,2,1,1
31,41,uncommented_buggy_41.sol,uncommented_renamed_buggy_41.sol,98,98,8,8,3,3,1,1,0,0
32,42,uncommented_buggy_42.sol,uncommented_renamed_buggy_42.sol,288,287,47,47,3,3,3,3,1,1
33,43,uncommented_buggy_43.sol,uncommented_renamed_buggy_43.sol,191,191,34,34,5,5,2,2,0,0
34,44,uncommented_buggy_44.sol,uncommented_renamed_buggy_44.sol,411,407,72,72,6,14,2,2,0,0
35,45,uncommented_buggy_45.sol,uncommented_renamed_buggy_45.sol,136,132,9,9,8,8,3,3,0,0
36,46,uncommented_buggy_46.sol,uncommented_renamed_buggy_46.sol,143,84,15,6,0,0,1,1,0,0
37,47,uncommented_buggy_47.sol,uncommented_renamed_buggy_47.sol,156,156,21,21,5,5,2,2,0,0
38,48,uncommented_buggy_48.sol,uncommented_renamed_buggy_48.sol,148,148,23,23,3,3,2,2,1,1
39,49,uncommented_buggy_49.sol,uncommented_renamed_buggy_49.sol,107,107,13,19,2,2,1,1,0,0
40,50,uncommented_buggy_50.sol,uncommented_renamed_buggy_50.sol,331,155,47,20,2,2,2,2,0,0
41,6,uncommented_buggy_6.sol,uncommented_renamed_buggy_6.sol,355,293,55,41,7,7,1,1,0,0
42,7,uncommented_buggy_7.sol,uncommented_renamed_buggy_7.sol,362,364,57,57,7,7,1,1,0,0
43,8,uncommented_buggy_8.sol,uncommented_renamed_buggy_8.sol,140,140,13,13,5,5,3,3,0,0
44,9,uncommented_buggy_9.sol,uncommented_renamed_buggy_9.sol,174,174,14,14,3,3,3,3,1,1

,file_number,original_file,renamed_file,original_lines_of_code,renamed_lines_of_code,original_number_of_function,renamed_number_of_function,original_number_of_event,renamed_number_of_event,original_number_of_struct,renamed_number_of_struct,original_number_of_library,renamed_number_of_library
0,18,uncommented_buggy_18.sol,uncommented_renamed_buggy_18.sol,272,272,32,32,4,4,2,2,2,2
1,19,uncommented_buggy_19.sol,uncommented_renamed_buggy_19.sol,145,174,30,30,0,0,2,3,1,1
2,24,uncommented_buggy_24.sol,uncommented_renamed_buggy_24.sol,450,451,29,30,0,0,4,5,1,1
3,25,uncommented_buggy_25.sol,uncommented_renamed_buggy_25.sol,312,334,31,31,7,7,3,3,0,0
4,26,uncommented_buggy_26.sol,uncommented_renamed_buggy_26.sol,145,145,25,25,4,4,1,1,1,1
5,30,uncommented_buggy_30.sol,uncommented_renamed_buggy_30.sol,626,575,77,77,9,9,1,1,2,2
6,31,uncommented_buggy_31.sol,uncommented_renamed_buggy_31.sol,128,128,9,9,2,2,3,3,1,1

Empty DataFrame
Columns: []
Index: []